### ISSUE TITLE
Relay not working

### ISSUE THREAD

**Issue by kabatp** [gabehf/Koito#35]
```
2025-06-26T20:05:09Z INF > Received POST /apis/listenbrainz/1/submit-listens - Responded with 200 in 128.51ms | request_id=U54oLhQe type=access
2025-06-26T20:05:10Z WRN > doLbzRelay: Non-2XX response from ListenBrainz relay | request_id=U54oLhQe response="<html>\r\n<head><title>410 Gone</title></head>\r\n<body>\r\n<center><h1>410 Gone</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n" status=410
```

No songs appear in ListenBrainz.

OS: TrueNAS Scale 25.04.1

Docker config:

```
services:
  db:
    container_name: psql
    environment:
      POSTGRES_DB: koitodb
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_USER: postgres
    image: postgres:16
    restart: unless-stopped
    volumes:
      - PATH:/var/lib/postgresql/data
  koito:
    container_name: koito
    depends_on:
      - db
    environment:
      - >-
        KOITO_DATABASE_URL=postgres://postgres:PASSWORD@db:5432/koitodb
      - KOITO_ALLOWED_HOSTS=IP_ADDRESS
      - KOITO_ENABLE_LBZ_RELAY=true
      - KOITO_LBZ_RELAY_URL=https://api.listenbrainz.org
      - KOITO_LBZ_RELAY_TOKEN=VALID_TOKEN_FROM_LISTEBNRAINZ
      - KOITO_LOG_LEVEL=info
    image: gabehf/koito:latest
    ports:
      - 'PORT:4110'
    restart: unless-stopped
    volumes:
      - PATH:/etc/koito
```
