### ISSUE TITLE
Failed to read image_cache full

### ISSUE THREAD

**Issue by kabatp** [gabehf/Koito#36]
```
Failed to read from directory /etc/koito/image_cache/full; skipping for prune |
```

When querying the path, the full folder does not exist:

![Image](https://github.com/user-attachments/assets/253b72e8-9e39-430e-9572-e2a106f328d6)

OS: TrueNAS Scale 25.04.1

Docker config:

```
services:
  db:
    container_name: psql
    environment:
      POSTGRES_DB: koitodb
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_USER: postgres
    image: postgres:16
    restart: unless-stopped
    volumes:
      - PATH:/var/lib/postgresql/data
  koito:
    container_name: koito
    depends_on:
      - db
    environment:
      - >-
        KOITO_DATABASE_URL=postgres://postgres:PASSWORD@db:5432/koitodb
      - KOITO_ALLOWED_HOSTS=IP_ADDRESS
      - KOITO_ENABLE_LBZ_RELAY=true
      - KOITO_LBZ_RELAY_URL=https://api.listenbrainz.org
      - KOITO_LBZ_RELAY_TOKEN=VALID_TOKEN_FROM_LISTEBNRAINZ
      - KOITO_LOG_LEVEL=info
    image: gabehf/koito:latest
    ports:
      - 'PORT:4110'
    restart: unless-stopped
    volumes:
      - PATH:/etc/koito
```
