### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by kabatp** [gabehf/Koito#7]
My current setup: Jellyfin to Koito to Listenbrainz

OS: TrueNAS 25.04

Error in logs:
```
Received GET /apis/listenbrainz/1/validate-token - Responded with 401 in 0.02ms | request_id=xWPN6bUC type=access
```

Jellyfin plugin used for LZB: https://github.com/lyarenei/jellyfin-plugin-listenbrainz
LZB API used: http://192.168.100.13:5005/apis/listenbrainz

Docker compose:
```
services:
  db:
    container_name: psql
    environment:
      POSTGRES_DB: koitodb
      POSTGRES_PASSWORD: nice-password
      POSTGRES_USER: postgres
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /mnt/Tank1/custom-apps/koito/db-data:/var/lib/postgresql/data
  koito:
    container_name: koito
    depends_on:
      - db
    environment:
      - >-
        KOITO_DATABASE_URL=postgres://postgres:nice-password@db:5432/koitodb
      - KOITO_ALLOWED_HOSTS=192.168.100.13:5005,192.168.100.13:30013
      - KOITO_ENABLE_LBZ_RELAY=true
      - KOITO_LBZ_RELAY_URL=https://api.listenbrainz.org
      - KOITO_LBZ_RELAY_TOKEN=nice-token-123
      - KOITO_LOG_LEVEL=info
    image: gabehf/koito:latest
    ports:
      - '5005:4110'
    restart: unless-stopped
    volumes:
      - /mnt/Tank1/custom-apps/koito/koito-data:/etc/koito
    ```
